# Generated by Django 6.0.7 on 2026-08-01 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payment",
            options={"ordering": ["-paid_at"]},
        ),
        migrations.AlterField(
            model_name="collect",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="collect",
            name="reason",
            field=models.CharField(
                choices=[
                    ("birthday", "День рождения"),
                    ("wedding", "Свадьба"),
                    ("travel", "Путешествие"),
                    ("education", "Образование"),
                    ("medical", "Медицина"),
                    ("other", "Другое"),
                ],
                default="other",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="collect",
            name="target_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Сумма, которую планируют собрать. Оставьте пустым для «бесконечного» сбора.",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="comment",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments_made",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
