# Generated by Django 6.0.7 on 2026-08-01 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("collects", "0002_alter_payment_options_alter_collect_description_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="collect",
            options={"ordering": ["-created_at"]},
        ),
        migrations.DeleteModel(
            name="Payment",
        ),
    ]
